volumes:
  node:
  dotnet-bin:
  dotnet-obj:
  db-data:

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/local/node/Dockerfile
    container_name: frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/src
      - ./logs/frontend:/root/.npm/_logs
      - node:/src/node_modules
    stdin_open: true
    tty: true
  backend:
    build:
      context: .
      dockerfile: docker/local/dotnet/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/src
      - dotnet-bin:/src/bin
      - dotnet-obj:/src/obj
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: docker/local/mssql/Dockerfile
    container_name: db
    user: root
    ports:
      - 1433:1433
    environment:
      - MSSQL_SA_PASSWORD=Passw0rd
    volumes:
      - ./logs/db:/var/opt/mssql/log
      - db-data:/var/opt/mssql
    command: [ "/bin/bash", "-c", "chmod +x /usr/src/app/entrypoint.sh && /usr/src/app/entrypoint.sh" ]
