# <https://github.com/hadolint/hadolint/blob/master/docs/INTEGRATION.md#github-actions>
name: Lint Dockerfile

on:
  push:
    branches: [ "develop" ]
    paths:
      - "**/Dockerfile"
  pull_request:
    branches: [ "develop" ]
    paths:
      - "**/Dockerfile"

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Lint Dockerfile (Local dotnet)
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "./docker/local/dotnet/Dockerfile"
      - name: Lint Dockerfile (Local mssql)
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "./docker/local/mssql/Dockerfile"
      - name: Lint Dockerfile (Local node)
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "./docker/local/node/Dockerfile"
      - name: Lint Dockerfile (Prod dotnet)
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "./docker/prod/dotnet/Dockerfile"
      - name: Lint Dockerfile (Prod mssql)
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "./docker/prod/mssql/Dockerfile"
      - name: Lint Dockerfile (Prod nginx)
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "./docker/prod/nginx/Dockerfile"
